# Multiple Linear Regression

Importing the libraries

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

   # Importing the dataset

In [8]:
dataset = pd.read_csv('Data_mODEL_SELECTION.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.48 431.23]
 [458.56 460.01]
 [462.74 461.14]
 ...
 [440.4  440.36]
 [452.23 451.22]
 [441.36 439.56]]


In [15]:
y_pred = regressor.predict(X_train)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

## Evaluating model performance

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9365341601931816

# Polynomial Regression

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
dataset = pd.read_csv('Data_mODEL_SELECTION.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [25]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly_reg = PolynomialFeatures(degree =4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
# Prediction

y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[433.82 431.23]
 [457.87 460.01]
 [460.32 461.14]
 ...
 [437.18 440.36]
 [451.42 451.22]
 [440.1  439.56]]


In [29]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.9470461951434421

# Random Forest Regression

In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [35]:
dataset = pd.read_csv('Data_mODEL_SELECTION.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [37]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor()
regressor.fit(X_train,y_train)

C:\Users\Deepak\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [38]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision  =2 )
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[435.24 431.23]
 [455.61 460.01]
 [464.8  461.14]
 ...
 [441.75 440.36]
 [453.76 451.22]
 [438.75 439.56]]


In [39]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.9627028598445958

In [ ]:
# 